# permissions for end users to view podmonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: podmonitor-viewer-role
rules:
- apiGroups:
  - pods.example.com
  resources:
  - podmonitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pods.example.com
  resources:
  - podmonitors/status
  verbs:
  - get
