name: gcp-gke-yaml
runtime: yaml
description: GCP GKE Cluster
resources:
  mygkecluster-yaml:
    type: gcp:container:Cluster
    properties:
      initialNodeCount: 1
      minMasterVersion: latest
      nodeVersion: latest
      nodeConfig:
        machineType: n1-standard-1
outputs:
  kubeconfig: ${mygkecluster-yaml.masterAuth.clusterCaCertificate}
