from kopf import on, create
from kubernetes import client, config

@kopf.on.event('', 'v1', 'pods', names=['test-completion-pod'])
def monitor_pod(spec, status, name, namespace, **kwargs):
    if status.get('phase') == 'Succeeded':
        # Create replacement pod
        api = client.CoreV1Api()
        pod_manifest = {
            'apiVersion': 'v1',
            'kind': 'Pod',
            'metadata': {
                'name': 'replacement-pod'
            },
            'spec': {
                'containers': [{
                    'name': 'replacement-container',
                    'image': 'alpine:latest',
                    'command': ['/bin/sh'],
                    'args': ['-c', 'echo "Replacement pod running"; sleep 30']
                }],
                'restartPolicy': 'Never'
            }
        }
        api.create_namespaced_pod(namespace=namespace, body=pod_manifest)

