apiVersion: v1
kind: Pod
metadata:
  name: notification-pod
spec:
  containers:
  - name: main-container
    image: alpine:latest
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "echo 'Container started'"]
      preStop:
        exec:
          command: ["/bin/sh", "-c", "echo 'Container stopping'"][10]

