apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: ethnode-uptime
  labels:
    service_name: ethnode
    feature_name: uptime
    slo_name: uptime
spec:
  description: Uptime of Ethereum node Pod
  backend: cloud_monitoring
  method: good_total_ratio
  exporters:
  - cloud_monitoring
  service_level_indicator:
    filter_good: >
      project=${GCP_PROJECT_ID}
      metric.type="kubernetes.io/pod/uptime"
      resource.type="k8s_pod"
      ( resource.labels.pod_name = "ethnode" )
    filter_valid: >
      project=${GCP_PROJECT_ID}
      metric.type="kubernetes.io/pod/uptime"
      resource.type="k8s_pod"
      ( resource.labels.pod_name = "ethnode" )
  goal: 0.9999