name: azure-aks-yaml
runtime: yaml
description: Azure AKS Cluster
resources:
  resourceGroup:
    type: azure-native:resources:ResourceGroup
  myakscluster-yaml:
    type: azure-native:containerservice:ManagedCluster
    properties:
      resourceGroupName: ${resourceGroup.name}
      agentPoolProfiles:
        - count: 1
          vmSize: Standard_DS2_v2
          name: agentpool
      dnsPrefix: myakscluster-yaml
outputs:
  kubeconfig: ${myakscluster-yaml.kubeConfigs[0].value}
