apiVersion: sdk.operatorframework.io/v1
kind: Operator
metadata:
  name: pod-monitor-operator
spec:
  components:
    - name: controller
      image: quay.io/operator-framework/helm-operator:v1.0.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-monitor-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-monitor-rolebinding
subjects:
- kind: ServiceAccount
  name: pod-monitor-operator
roleRef:
  kind: Role
  name: pod-monitor-role
  apiGroup: rbac.authorization.k8s.io

