apiVersion: v1
kind: Pod
metadata:
  name: continuous-running-pod
spec:
  containers:
  - name: alpine-container
    image: alpine:latest
    command: ["/bin/sh"]
    args:
    - -c
    - |
      while true; do
        echo "Pod is running... $(date)"
        sleep 30
      done

