name: eks-yaml
runtime: yaml
description: Minimal EKS cluster
resources:
  my-cluster-yaml:
    type: eks:Cluster
    properties:
      desiredCapacity: 1
      minSize: 1
      maxSize: 1
      instanceType: t3.micro
outputs:
  kubeconfig: ${my-cluster-yaml.kubeconfig}
